### ISSUE TITLE
Rewrite client it in elixir

### ISSUE THREAD

**Issue by slashmili** [slashmili/alchemist.vim#10]
Rewrite? First need to check the performance of the client in elixir

**Comment by slashmili** [comment]
Since we have some neovim users here, I decided to keep client in python

also elixir script runs significantly slower than a python script

```
$ time elixir e.exs
"hello"

real	0m0.304s
user	0m0.307s
sys	0m0.202s
$ time python p.py
hello

real	0m0.031s
user	0m0.012s
sys	0m0.016s
bash-3.2$
```

**Comment by hauleth** [comment]
That is why there should be long running process in the background which will exchange information with Vim/NeoVim via pipes.

Both Vim 8 and NeoVim have support for background jobs which we should leverage for completion.

**Comment by slashmili** [comment]
Let's start from #117 and see where can we go from there.
