### ISSUE TITLE
GoTo definition (Control+]) does not work on projects but Erlang/Elixir source code

### ISSUE THREAD

**Issue by atlas-comstock** [slashmili/alchemist.vim#100]
Can not jump to my projects' def though I had done `mix compile`.
Thanks.

**Comment by slashmili** [comment]
@YongHaoWu try to follow the debugging steps in [Debugging](https://github.com/slashmili/alchemist.vim/wiki/%5BWIP%5D-Debugging) page and let me know the result

**Comment by atlas-comstock** [comment]
Hey, @slashmili . Thank you for your reply.
Both `DEFL { "CustomModule,foo", [ context: Elixir, imports: [], aliases: [] ] }` and `DEFLX { "CustomModule.foo", [ context: Elixir, imports: [Quickfix], aliases: []] }` not works.

Here is my commands:
```
~/mycode/ejoy/battleship/src/gangplank/apps/nurse on  nurse! ⌚ 17:12:09
$ ~/.vim/bundle/alchemist.vim/alchemist_client -d ./
DEFL { "CustomModule,foo", [ context: Elixir, imports: [], aliases: [] ] }

END-OF-DEFL

~/mycode/ejoy/battleship/src/gangplank/apps/nurse on  nurse! ⌚ 17:12:10
$ ~/.vim/bundle/alchemist.vim/alchemist_client -d ./
DEFLX { "CustomModule.foo", [ context: Elixir, imports: [Quickfix], aliases: []] }
END-OF-DEFLX%
~/mycode/ejoy/battleship/src/gangplank/apps/nurse on  nurse! ⌚ 17:12:22
$ ls lib/custom_module.ex
lib/custom_module.ex

~/mycode/ejoy/battleship/src/gangplank/apps/nurse on  nurse! ⌚ 17:12:53
$ cat lib/custom_module.ex
defmodule CustomModule do
  def foo do
    :ok
  end
end
```

**Comment by connorlay** [comment]
@YongHaoWu When you execute those commands, are you in your `nurse/lib` directory where `custom_module.ex` is located?

**Comment by atlas-comstock** [comment]
@connorlay I am in `nurse` directory. But I try `nurse/lib`, the same output as in `nurse`.
Thanks.

**Comment by atlas-comstock** [comment]
@slashmili @connorlay I forgot to mentioned that it works in Elixir code. Means that I can jump to Elixir's code from my project's code, e.g, `Enum.reduce`

**Comment by slashmili** [comment]
@YongHaoWu can you run the command on the main project directory?

in [vimscript](https://github.com/slashmili/alchemist.vim/blob/master/after/plugin/alchemist.vim#L481) we find the main directory but if you run it manually you should run it in the main directory.

**Comment by atlas-comstock** [comment]
@slashmili Hi, sry for the late reply.
Yep, it works in main project directory.
See
```
~/mycode/NeteaseCloudMusicFlacElixir/downloader on  master ⌚ 16:43:57
$ ~/.vim/bundle/alchemist.vim/alchemist_client -d ./
DEFLX { "CustomModule.foo", [ context: Elixir, imports: [Quickfix], aliases: []]                         D /Users/yonghaohu/mycode/NeteaseCloudMusicFlacElixir/downloader/lib/custom_module.ex:2
END-OF-DEFLX%
~/mycode/NeteaseCloudMusicFlacElixir/downloader on  master ⌚ 16:44:09
$ ~/.vim/bundle/alchemist.vim/alchemist_client -d ./
DEFLX { "Songlist.fetch_song_list", [ context: Elixir, imports: [Quickfix], aliases: []] }
/Users/yonghaohu/mycode/NeteaseCloudMusicFlacElixir/downloader/lib/songlist.ex:2
END-OF-DEFLX%
```

It works in a small project now! Thanks.

But will it doesn't work on **umbrella projects**, e.g, I have a umbrella projects named `gangplank`(can not compile due to different dependencies), sub-project `nurse` compiled successfully. 
```
~/mycode/ejoy/battlenet/gangplank/apps/nurse on  nurse! ⌚ 16:52:27
$ ~/.vim/bundle/alchemist.vim/alchemist_client -d ./
DEFLX { "CustomModule.foo", [ context: Elixir, imports: [Quickfix], aliases: []] }
END-OF-DEFLX%
~/mycode/ejoy/battlenet/gangplank/apps/nurse on  nurse! ⌚ 16:52:35
$ ~/.vim/bundle/alchemist.vim/alchemist_client -d ./
DEFL { "CustomModule,foo", [ context: Elixir, imports: [], aliases: [] ] }

END-OF-DEFL
```

**Comment by atlas-comstock** [comment]
@slashmili Do u have any idea to fix this?
Or I have to compile whole projects?

**Comment by slashmili** [comment]
@YongHaoWu the program is piggy backing the elixir compile directory structure and if it can't compile the whole project it won't work :(

**Comment by atlas-comstock** [comment]
@slashmili Oh, that's a pity :(  Thanks for your work! It is wonderful.
PS: ctags don't work for me （https://github.com/mmorearty/elixir-ctags/issues/6）

**Comment by slashmili** [comment]
@YongHaoWu ctags also works based on compiled file :(

**Comment by atlas-comstock** [comment]
@slashmili Yeah, it's just another topic. Anyway, my issue is solved now(knowing that it need to be compiled all). Thanks.
