### ISSUE TITLE
Completion not working with multiple import

### ISSUE THREAD

**Issue by ashervb** [slashmili/alchemist.vim#101]
Given the follow module definition, when I type `period` where it says `<Type Period>`, no PUM opens
```elixir
defmodule MyModule do
  import Ecto.{Query, Changeset}

  def foo do
    Enum<Type Period>
  end
end
```

However if I change the imports to:

```elixir
defmodule MyModule do
  import Ecto.Query
  import Ecto.Changeset

  def foo do
    Enum<Type Period>
  end
end
```
I get the full list of module completions as expected:

![elixir](https://user-images.githubusercontent.com/1232199/27520596-d61b25f6-59c3-11e7-891f-94987916e2dd.png)

I'm on:

```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.5
```

**Comment by slashmili** [comment]
@exitface I'll take a look.

Thanks for reporting it.

**Comment by slashmili** [comment]
@exitface just noticed that we never implement multiple import! 😞 

It would be something like PR #94

**Comment by slashmili** [comment]
@exitface thanks for reporting the issue

I'm working on [elixir-sense](https://github.com/slashmili/alchemist.vim/tree/elixir-sense) which solves lots of problem like this.

I keep the issuer open until that new feature is ready

**Comment by slashmili** [comment]
@exitface please try the new version
