### ISSUE TITLE
Deoplete remote plugin truncates the last completion

### ISSUE THREAD

**Issue by rlbaker** [slashmili/alchemist.vim#103]
Currently, the deoplete remote plugin for alchemist.vim appears to truncate the last completion from the list. I've done my best to illustrate the issue I'm seeing below in images and alchemist-server communications. From looking at the code, it appears that the `-2` in the split should in fact be a `-1`. I've opened a [PR](https://github.com/slashmili/alchemist.vim/pull/102) with this (extremely tiny) change.

## Current Behavior (split on `-2`)
![Current Behavior](http://imgur.com/hyHGdqa.jpg)

### Full server response
```
"kind:f, word:Sandbox.functionA, abbr:functionA/1\nkind:f, word:Sandbox.functionB, abbr:functionB/2\nkind:f, word:Sandbox.functionC, abbr:functionC/3\nEND-OF-COMPX"
```

### Split response

```
[ "kind:f, word:Sandbox.functionA, abbr:functionA/1", 
  "kind:f, word:Sandbox.functionB, abbr:functionB/2" ]
```

## After fix (split on `-1`)
![Behavior after fix](http://imgur.com/1Kjfl0C.jpg)

### Full server response
```
"kind:f, word:Sandbox.functionA, abbr:functionA/1\nkind:f, word:Sandbox.functionB, abbr:functionB/2\nkind:f, word:Sandbox.functionC, abbr:functionC/3\nEND-OF-COMPX"
```

### Split response

```
[ "kind:f, word:Sandbox.functionA, abbr:functionA/1", 
  "kind:f, word:Sandbox.functionB, abbr:functionB/2",
  "kind:f, word:Sandbox.functionC, abbr:functionC/3" ]
```

**Comment by slashmili** [comment]
thanks @rlbaker 🎉
