### ISSUE TITLE
Syntax highlighting?

### ISSUE THREAD

**Issue by kuwze** [slashmili/alchemist.vim#111]
I am not using autocomplete at the moment, but I was just wondering about syntax highlighting. I tried enabling and disabling this plugin but there was no difference in the syntax highlighting. Should I be using another plugin for that?

**Comment by kuwze** [comment]
It looks like syntax-highlighting is provided by vim-polyglot with the following install:
Plug 'sheerun/vim-polyglot'

**Comment by slashmili** [comment]
Correct, [check out wiki page](https://github.com/slashmili/alchemist.vim/wiki#dependencies)
