### ISSUE TITLE
ExDef not consistent with ExDoc

### ISSUE THREAD

**Issue by indera** [slashmili/alchemist.vim#114]
ExDoc opens a split window - https://github.com/slashmili/alchemist.vim/blob/76fac04c3edc86a7ff9d1b425a8778efcdc97740/after/plugin/alchemist.vim#L200

But ExDef edits a file and the user has to go back and re-open the file
https://github.com/slashmili/alchemist.vim/blob/76fac04c3edc86a7ff9d1b425a8778efcdc97740/after/plugin/alchemist.vim#L247

Am I doing something incorrectly? I expected ExDef to open a tab so I can view the implementation of a module. 

==
Editor: NVIM v0.2.0
Plugins:

- vim-polyglot: OK
- awesome-vim-colorschemes: OK
- alchemist.vim: OK
- tagbar: OK
- phoenix.vim: OK
- deoplete.nvim: OK
- vim-elixir: OK
- nerdtree: OK (not loaded)
- vim-endwise: OK
- vim-projectionist: OK
- elixir_generator.vim: OK
- vim-airline-themes: OK
- vim-gutentags: OK
- neomake: OK
- elixir-ctags: OK
- ctrlp.vim: OK
- vim-extest: OK
- vim-airline: OK
- vim-eh-docs: OK
- vim-mix: OK

==================
System info - MacOS:

Erlang/OTP 20 [erts-9.0.4] [source] [64-bit] 
Interactive Elixir (1.5.1)

**Comment by slashmili** [comment]
@indera, well you are kinda right. However the idea is you jump to a definition of probably your function and want to edit the code or you might want to go deeper.

When I implemented ExDef I was thinking of a replacement for TAGs.

In TAGs, you can press `<Ctrl>+]` to jump to a definition and use `<Ctrl>+t` to go back to your previous locations

**Comment by indera** [comment]
Should I close this issue?
I used this workaround:

autocmd FileType elixir nnoremap <buffer> <leader>d :vsplit<CR> :call alchemist#exdef()<CR>
