### ISSUE TITLE
Provide asynchronous features

### ISSUE THREAD

**Issue by hauleth** [slashmili/alchemist.vim#117]
This would simplify integration with modern completion frameworks other than deoplete.

**Comment by slashmili** [comment]
@hauleth how would you suggest to that?

BTW we should support python3 before(related to ticket #110)

**Comment by hauleth** [comment]
@slashmili for now function that return command to be ran and parser for the elixir_sense output format would be enough. Alternatively this could be done through `job-control` (NeoVim) and `channels` (Vim 8+).

**Comment by slashmili** [comment]
@hauleth considering adding the autocomplete to asynchronous autocomplete framework is easy as shown in #120, I suppose we don't need this anymore.

let me know if you think otherwise and why do you think so.
