### ISSUE TITLE
MapSet not found

### ISSUE THREAD

**Issue by jayceekay** [slashmili/alchemist.vim#123]
i don't think this is a real issue so i didn't fill out the issue form, forgive me for that if i'm wrong. alchemist isn't able to find the definition for MapSet when i do `K` over it - did i miss a setup step? i'm guessing it has to do with it not finding the elixir/erlang source code, although it works fine for other modules like Enum.

**Comment by slashmili** [comment]
@jayceekay I tried it locally and looks like it's related to `elixir_sense`.

I'll open an issue for this in `elixir_sense`

**Comment by jayceekay** [comment]
was there any followup to this?

**Comment by slashmili** [comment]
@jayceekay I've updated elixir_sense and it's working now. Please update  `alchemist.vim` and try again
