### ISSUE TITLE
YouCompleteMe — No semantic completer exists for filetypes: ['elixir']

### ISSUE THREAD

**Issue by gj** [slashmili/alchemist.vim#127]
1. Elixir/OTP/Python version
    - Elixir: 1.6.1
    - OTP: 20
    - Python: 3.6.4

2. Which pluging are you using:
    - [ ] basic omnifunc
    - [x] YouCompleteMe
    - [ ] deoplete

3. Which steps of Debugging passed?
    - [x] Elixir Module definition
    - [x] Elixir Function definition
    - [x] Elixir Module/Function docs
    - [ ] Your Project Module definition
    - [ ] Your Project Function definition

4. Do you have a specific setup? Like Docker and etc
    - Vim and Elixir installed via Homebrew. YCM and Alchemist.vim installed via vim-plug.

Both [Lookup Project's Library commands from the Debugging page](https://github.com/slashmili/alchemist.vim/wiki/Debugging#lookup-projects-library) return `non_existing:0`, and in the YouCompleteMe server stderr logs I see a ton of `ERROR - No semantic completer exists for filetypes: ['elixir']`. YCM seems to work fine for other languages.

**Comment by slashmili** [comment]
@gj sorry for late response. 

Do you have your dotfile somewhere I can try it locally?

**Comment by gj** [comment]
@slashmili no problem at all! Appreciate all of your hard work on this OSS. Here are my dotfiles: https://github.com/gj/.dotfiles

**Comment by slashmili** [comment]
@gj did you try `mix compile` before running the debugging command? It's written in small note in Debug page

```
~/d/boo $ ~/.vim/plugged/alchemist.vim/elixir_sense_client -d./ -c1 -l2 --request=definition < sample.exs
non_existing:0⏎                                                                                                                                                                                                                        
~/d/boo $ mix compile
Compiling 1 file (.ex)
Generated boo app
~/d/boo $ ~/.vim/plugged/alchemist.vim/elixir_sense_client -d./ -c1 -l2 --request=definition < sample.exs
/Users/slashmili/dev/boo/lib/custom_module.ex:1⏎
```

**Comment by gj** [comment]
Can't reproduce anymore. Thanks!
