### ISSUE TITLE
Phoenix support

### ISSUE THREAD

**Issue by slashmili** [slashmili/alchemist.vim#13]
I'm not sure about the commands we need to support but [vim-rails](https://github.com/tpope/vim-rails) looks good

**Comment by aerosol** [comment]
FWIW, looking at `vim-rails` I don't think there's anything Phoenix specific to support. 
Alternating between files can be done with `vim-projectionist`. Hope that helps.

**Comment by slashmili** [comment]
Also `vim-rails` is not my favourite. I need to look at `alchemist.el` and see what they have done there.

Maybe we can drop this feature.

**Comment by aerosol** [comment]
+1 for dropping it. I really like this plugin and my concern is it'll get too bloated for "the vim way".

**Comment by slashmili** [comment]
OK
