### ISSUE TITLE
Change paths returend by elixir sense

### ISSUE THREAD

**Issue by bitboxer** [slashmili/alchemist.vim#132]
Small question: I have an elixir project that uses docker heavily. The files are all mounted inside of a docker container and the build is happening there. That leads to the problem that the build has wrong paths that only work inside of the docker container. Because of that my vim running outside of it does not find the correct files to jump to when using alchemist. Is it possible to configure alchemist to change the path if the prefix is `/app/` to the current project path?

**Comment by slashmili** [comment]
@bitboxer take a look at this guide https://github.com/slashmili/alchemist.vim/blob/master/doc/alchemist.txt#L55

It's a bit inconvenient because it effects your vim global settings. Checkout #78 there are some suggestion how to use it with vim-localvimrc

**Comment by bitboxer** [comment]
Thanks! Sorry that I missed that in the docs.

**Comment by slashmili** [comment]
No worries, it's bit hidden :)

Let me know if it works for you or not. I don't use it often.

**Comment by bitboxer** [comment]
It now opens the correct file, but sadly it does not jump to the line inside of the file.

**Comment by slashmili** [comment]
I though you don't like the jump to def in Alchemist.vim 😄 

So after we moved to elixir_sense, `elixir_sense` is the one that finds the location of function but I remember it didn't work when loading beam from docker compiled files. I need to take a look at it again.

**Comment by bitboxer** [comment]
Okay, understood. Really looking forward to the fixed version. Sadly due to my new baby my time is limited and I can't really offer to help, but if this isn't fixed in 2-3 weeks, I might have some time to look into it, too
