### ISSUE TITLE
Auto-complete with YouCompleteMe makes backspacing very slow

### ISSUE THREAD

**Issue by jswny** [slashmili/alchemist.vim#133]
# Issue
In a basic Elixir project, enabling YouCompleteMe and Alchemist.vim makes backspacing **slow and clunky**. Backspacing during auto-completion (a lot of the time) is awkward and slow enough that I can't keep YouCompleteMe enabled because of it.

[Screencast of backspacing **without** auto-completion turned on](https://asciinema.org/a/WpRDsEgZge7Z9KAEVUNaG7aqc)

[Screencast **with** auto-completion turned on](https://asciinema.org/a/gB7fcV8CnUy6zvKEMgy0xiGeS)

Other auto-completion modules **do not** suffer from this slowness. I have tested JS and Python. My hardware is pretty good, and the slowness in backspacing is still felt on my 2015 MacBook Pro (i7), and my 2017 iMac (quad core i7).

I don't know if this is "intended behavior" in that I'm not supposed to have auto-complete on all the time, but I would like to have it on all the time like I do in my IDE's.

Thanks very much for your hard work on this project!

# Details
1. Elixir/OTP/Python version

Elixir: `1.6.0`

OTP: `20.0`

Python: `3.6.4`

2. Are you using VIM or Neovim? Please provide the version.
MacVim `mvim 8.0.1633`  (command line)

3. Which pluging are you using:

[ ] basic omnifunc
[x] YouCompleteMe
[ ] deoplete

4. Which steps of Debugging passed?

N/A

5. Do you have a specific setup? Like Docker and etc
Just MacOS High Sierra.

**Comment by slashmili** [comment]
@jswny I'm not YouCompleteMe user so it's hard to say why is it work like that.

Do you have your vimrc somewhere? I can give it a try locally.

What I've seen is autocomplete modules usually cache the results but looks like that in your case it's asking `alchemist.vim` to give hint on each change.

I'll try it locally and update you

**Comment by jswny** [comment]
Thanks! I would try deoplete but it seems like it is geared towards NeoVim, which I'm not using. It is clearly asking for hints on each change, which is preventing me from backspacing until it is done checking. I don't know how these things work of course but it seems like those things should be separate and asynchronous, and that suggestions shouldn't interfere with typing.

Here is my `.vimrc`:
```
"""""
" Dependencies
"""""

" YouCompleteMe (with appropriate languages installed) - https://github.com/Valloric/YouCompleteMe
" FZF - https://github.com/junegunn/fzf 
" For Alchemist.vim:
" " Python 2 (see https://github.com/slashmili/alchemist.vim/issues/116 for troubleshooting)
" " Also see https://github.com/slashmili/alchemist.vim/wiki/Debugging to verify everything is working

"""""
" End Dependencies
"""""

"""""
" General
"""""

" Turn syntax highlighting on
:syntax on

" Fix backspace so that it works normally
set backspace=indent,eol,start

" Indentation settings
" show existing tab with 2 spaces width
set tabstop=2
" when indenting with '>', use 2 spaces width
set shiftwidth=2
" On pressing tab, insert 2 spaces
set expandtab

" Turn case sensitive search off and smartcase search on
:set ignorecase
:set smartcase

" Turn on line numbers
:set number

" Allow buffer switching without saving
set hidden

" Add fzf base plugin
set rtp+=/usr/local/opt/fzf

"""""
" End General
"""""

"""""
" Key Bindings 
"""""

" Shortcut to Vim Buffkill a buffer with CTRL+C
" map <C-c> :BD<cr>

" Shortcut to FZF :Files with \f
nnoremap <leader>f :Files<cr>

" Shortcut to FZF :Buffers with \b
nnoremap <leader>b :Buffers<cr>

" Shortcut to FZF :Lines with \l
nnoremap <leader>l :Lines<cr>

"""""
" End Key Bindings
"""""

""""" 
" Vundle
"""""
set nocompatible " be iMproved, required
filetype off     " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Installed plugins
Plugin 'elixir-lang/vim-elixir'
Plugin 'slashmili/alchemist.vim'
Plugin 'leafgarland/typescript-vim'
Plugin 'tpope/vim-endwise'
" Plugin 'scrooloose/nerdtree'
" Plugin 'Xuyuanp/nerdtree-git-plugin'
" Plugin 'qpkorr/vim-bufkill'
Plugin 'scrooloose/nerdcommenter'
Plugin 'airblade/vim-gitgutter'
Plugin 'alvan/vim-closetag'
Plugin 'junegunn/fzf.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'Valloric/YouCompleteMe'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
"""""
" End Vundle
"""""

"""""
" NERD Commenter
"""""

" Add a space for all comments
let NERDSpaceDelims=1

"""""
" End NERD Commenter
"""""

"""""
" YouCompleteMe
"""""

" Disable global auto-completion
let g:ycm_auto_trigger = 0

"""""
" End YouCompleteMe
"""""

"""""
" Vim Closetag
"""""

" Add *.eex to the file types in which tags get auto-closed
let g:closetag_filenames = '*.html,*.xhtml,*.phtml,*.eex'

"""""
" End Vim Closetag
"""""

```

**Comment by jswny** [comment]
I am now using Deoplete with NeoVim, and it works like a charm! However, this issue still remains, so I will leave it up to @slashmili to decide if he wants to close it or not.

**Comment by slashmili** [comment]
I close this issue for now
