### ISSUE TITLE
Not :ExDoc nor `K` while over keyword works

### ISSUE THREAD

**Issue by FredrikAugust** [slashmili/alchemist.vim#138]
1. Elixir/OTP/Python version

Elixir: 1.7.1

OTP: 21

Python: 3.6.6

2. Are you using VIM or Neovim? Please provide the version.

Neovim 0.3.1

3. Which pluging are you using:

[ ] basic omnifunc
[ ] YouCompleteMe
[x] deoplete

4. Which steps of Debugging passed?

[ ] Elixir Module definition

When trying to go to definition of `defmodule` I get the following errror:

```
alchemist.vim: failed with message error:protocol Enumerable not implemented for nil                                                                                          
```

[ ] Elixir Function definition
[ ] Elixir Module/Function docs
[x] Your Project Module definition
[x] Your Project Function definition

**Comment by slashmili** [comment]
@FredrikAugust I'll update my OTP and check it out

**Comment by slashmili** [comment]
@FredrikAugust please update the plugin and give it a try again

**Comment by FredrikAugust** [comment]
It works now @slashmili, but when trying to get documentation for something under the cursor that doesn't exist it shows `Alchemist: No matches for ''!`, think that's a bug.

Great work though :))

**Comment by FredrikAugust** [comment]
And when I try to get documentation for a module I created it only shows the first line of the `moduledoc`. But I suppose that may be another issue.

**Comment by slashmili** [comment]
hmm strange, works for 😬 

Can you run the [debug](https://github.com/slashmili/alchemist.vim/wiki/Debugging) and paste the documentation output for me?

To execute it, create an empty file `sample.exs`, put the your modules in the first line and execute this
```
~/.vim/bundle/alchemist.vim/elixir_sense_client -d./ -c2 -l1 --request=docs < sample.exs
```

**Comment by FredrikAugust** [comment]
Going out now, but can try when I get home. 


Sent from my Samsung Galaxy smartphone.
null

**Comment by FredrikAugust** [comment]
```
No documentation available%
```

**Comment by slashmili** [comment]
hmmm, did you compile the project before looking for docs? And not sure what is `%` at the end of output 🤔

**Comment by slashmili** [comment]
Please update the plugin and try again. I close this issue for now
