### ISSUE TITLE
K shows `Alchemist: No matches for ''!` instead of documentation

### ISSUE THREAD

**Issue by egidijusz** [slashmili/alchemist.vim#139]
Hello,
doing "K" over any module/function shows "Alchemist: No matches for ''!".
This started happening some time ago (maybe ~2 weeks). 

Doing `elixir_sense_client -d./ -c6 -l3 --request=docs < sample.exs` shows "No documentation available". 
I've tried this command to get documentation of functions that are in the same project (in case alchemist can't find erlang/elixir source files) - same output.

All other functionalities of plugin work fine (autocomplete, jumping to source files and etc.).

1. Elixir/OTP/Python version

Elixir: 1.7.2

OTP: 21.0.5

Python: 3.7

2. Are you using VIM or Neovim? Neovim, version 0.3.1

3. Which pluging are you using:

[ ] basic omnifunc
[ ] YouCompleteMe
[x] deoplete

4. Which steps of Debugging passed?

[x] Elixir Module definition
[x] Elixir Function definition
[ ] Elixir Module/Function docs
[x] Your Project Module definition
[x] Your Project Function definition

5. Do you have a specific setup? Like Docker and etc
No.

**Comment by slashmili** [comment]
Hey @egidijusz 

I'm in process of updating [elixir_sense](https://github.com/msaraiva/elixir_sense) which solves the problem you have mentioned. I'm hoping that it will be ready by the end of this week

**Comment by slashmili** [comment]
@egidijusz please update the plugin and give it a try again

**Comment by egidijusz** [comment]
Fixed.

Thank you for your work and this great plugin, you're awesome!
