### ISSUE TITLE
Dependency on syslog python module breaks Windows compatibility

### ISSUE THREAD

**Issue by ilkka** [slashmili/alchemist.vim#140]
On Windows Python doesn't have that module but e.g. `elixir_sense.py` depends on it. You might want to either ship a [shim](https://stackoverflow.com/a/27661799/15064) or maybe depend on some library that abstracts it away.

**Comment by ilkka** [comment]
Ah, actually that's not enough because `elixir_sense.py` also does some manual path building at https://github.com/slashmili/alchemist.vim/blob/35e7e3062d1661b1c081765ed05bd8f0f5265183/elixir_sense.py#L218 which doesn't work on Windows.

**Comment by ilkka** [comment]
And now that I started drafting a PR to address this, there are even trickier bits like how one branch of `_get_tmp_dir` defaults to `/tmp/alchemist_server'. I guess it would be possible to have win / not-win branches with the win branch using something like `c:\temp\alchemist_server` but it's not pretty. Would it be possible to just use `tempfile.mkdtemp` even though I guess the dir has to be persistent?

**Comment by slashmili** [comment]
Hi @ilkka, sorry for the late response.

The syslog is only there for debugging purpose, we can disable that module in windows.

Same goes for the `alchemist_server` we can return different value when this is running on windows.

https://docs.python.org/3/library/os.html#os.name
