### ISSUE TITLE
K / ExDoc loses last line of documentation

### ISSUE THREAD

**Issue by jschomay** [slashmili/alchemist.vim#142]
K/ExDoc shows docs as expected in the preview window, but the docs are missing the last line.

Run `:ExDoc is_tuple` as an example.  

The last line of the docs should read "Allowed in guard tests. Inlined by the compiler."  However, for me, that line is missing.  This is true for any term, internal or external.  I am not sure if this is related to some other problem with my set up, or specific to Alchemist.  Does anyone else have this problem?

Thank you for looking into it!

1. Elixir/OTP/Python version

Elixir: 1.6.5

OTP: 20

Python: 3.6.3

2. Are you using VIM or Neovim? Please provide the version.
Happens in both Nvim 0.2.0 and Vim 8.0.

3. Which pluging are you using:

[ X] basic omnifunc
[ ] YouCompleteMe
[ ] deoplete

4. Which steps of Debugging passed?

[ ] Elixir Module definition
[ ] Elixir Function definition
[ ] Elixir Module/Function docs
[ ] Your Project Module definition
[ ] Your Project Function definition

All work, aside from the last line getting cut off in all cases

5. Do you have a specific setup? Like Docker and etc
On OSX High Sierra with iTerm2

**Comment by slashmili** [comment]
@jschomay thanks for reporting it!

Looks like that the elixir_sense_client gets the full docs. 
```
~/.vim/bundle/alchemist.vim/elixir_sense_client -d./ -c4 -l1 --request=docs
is_tuple
> Kernel.is_tuple(term)

### Specs

`@spec is_tuple(term) :: boolean`

Returns `true` if `term` is a tuple; otherwise returns `false`.

Allowed in guard tests. Inlined by the compiler.
```

I suppose somewhere in vimscript, the last line gets trimmed. I'll take a look
