### ISSUE TITLE
Suggestions dont show up for deoplete

### ISSUE THREAD

**Issue by rix501** [slashmili/alchemist.vim#144]
If autocomplete/docs or etc doesn't work for you
before creating issue please check Debugging page and make sure your basic setup works

https://github.com/slashmili/alchemist.vim/wiki/Debugging

and answer these questions:

1. Elixir/OTP/Python version

Elixir: 1.7

OTP: 20 

Python: 3

2. Are you using VIM or Neovim? Please provide the version.
Neovim 0.3.1

3. Which pluging are you using:

[ ] basic omnifunc
[ ] YouCompleteMe
[x] deoplete

4. Which steps of Debugging passed?

[x] Elixir Module definition
[x] Elixir Function definition
[x] Elixir Module/Function docs
[x] Your Project Module definition
[x] Your Project Function definition

5. Do you have a specific setup? Like Docker and etc
n/a

Deoplete won't load any alchemist suggestions but I can load the suggestions if I use the built in key mapping

**Comment by slashmili** [comment]
@rix501 I just updated my setup to use nvim `v0.3.4` and the latest deoplete.nvim. It works for me :/

Do you have deoplete.nvim for any other file format? Just want to make sure your deoplete.nvim is working

**Comment by rix501** [comment]
I forgot to install a dependency for deoplete. Thanks for checking!
