### ISSUE TITLE
something wrong editing the elixir code with spacevim

### ISSUE THREAD

**Issue by CellPhoneYeah** [slashmili/alchemist.vim#149]
** something wrong editing the elixir code with spacevim using slashmili **
ubuntu18.4, I want to edit the elixir code with spacevim, so I modified the configuration according to the official tutorial, but there was a problem when editing, although I reinstallation ubuntu system and spacevim many times

1.  Elixir/OTP/Python version
Elixir:1.7.3
OTP:20.3
Python:3.6.7
vim8.0

![QQ图片20190310171027](https://user-images.githubusercontent.com/19988436/54082917-b0446980-4357-11e9-9ff8-d8930489781c.png)

**Comment by slashmili** [comment]
Haven't seen this error before. Any idea @wsdjeg ?
