### ISSUE TITLE
ExDoc is wrong arity for function called in 'pipeline'

### ISSUE THREAD

**Issue by kenny-evitt** [slashmili/alchemist.vim#158]
## Questions:

1. Elixir/OTP/Python version

Elixir: 1.8.0

OTP: 21.2.3

Python: `python --version` reports `Python 2.7.16`

2. Are you using VIM or Neovim? Please provide the version.

I'm using VimR 0.27.5 (327) which uses Neovim. The output of the `:version` command:

```
NVIM v0.3.8
Build type: Release
LuaJIT 2.0.5
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -mmacosx-version-min=10.13 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -I/Users/hat/.jenkins/workspace/vimr_build/NvimView/neovim/build/config -I/Users/hat/.jenkins/workspace/vimr_build/NvimView/neovim/src -I/Users/hat/.jenkins/workspace/vimr_build/NvimView/neovim/.deps/usr/include -I/Users/hat/.jenkins/workspace/vimr_build/NvimView/third-party/libintl/include -I/usr/include -I/Users/hat/.jenkins/workspace/vimr_build/NvimView/neovim/build/src/nvim/auto -I/Users/hat/.jenkins/workspace/vimr_build/NvimView/neovim/build/include
Compiled by hat@iota.fritz.box

Features: +acl +iconv +jemalloc -tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

3. Which pluging are you using:

 - [ ] basic omnifunc
 - [ ] YouCompleteMe
 - [ ] deoplete

4. Which steps of Debugging passed?

 - [x] Elixir Module definition
 - [x] Elixir Function definition
 - [x] Elixir Module/Function docs
 - [x] Your Project Module definition
 - [x] Your Project Function definition

5. Do you have a specific setup? Like Docker and etc

I don't think so.

## Problem

Given code like this:

```elixir
some_enum
|> Enum.reduce(acc, fn e, acc -> ... end)
```

If I use the ExDoc shortcut on `reduce` I get the `Enum.reduce/2` docs instead of the `Enum.reduce/3` docs.

I'm guessing this might be an upstream issue, i.e. for ElixirSense itself. If that's the case, I'll open an issue for its project too.

**Comment by slashmili** [comment]
@kenny-evitt Yes it's coming from`ElixirSense`

**Comment by kenny-evitt** [comment]
I opened an issue for this in the ElixirSense GitHub project. [See the link above automatically added by GitHub.]

**Comment by slashmili** [comment]
Thanks, I close the ticket here for now
