### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by freevova** [slashmili/alchemist.vim#159]
When I try to use any of the functionality of the plugin, such as jump to definition, I get this python traceback at the very beginning:
```
[deoplete] Traceback (most recent call last):
  File "/home/vova/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/child.py", line 192, in _gather_results
    result = self._get_result(context, source)
  File "/home/vova/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/child.py", line 253, in _get_result
    ctx['candidates'] = source.gather_candidates(ctx)
  File "/home/vova/.vim/bundle/alchemist.vim/rplugin/python3/deoplete/sources/alchemist.py", line 33, in gather_candidates
    response = self.sense_client.process_command('suggestions', "\n".join(lines), lnum ,cnum)
  File "/home/vova/.vim/bundle/alchemist.vim/elixir_sense.py", line 56, in process_command
    sock = self.__get_socket()
  File "/home/vova/.vim/bundle/alchemist.vim/elixir_sense.py", line 86, in __get_socket
    self._run_alchemist_server(server_log)
  File "/home/vova/.vim/bundle/alchemist.vim/elixir_sense.py", line 243, in _run_alchemist_server
    subprocess.Popen(arg, stdout=log_file, stderr=log_file, stdin=log_file, cwd=self._cwd)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'elixir': 'elixir'
Error from alchemist: [Errno 2] No such file or directory: 'elixir': 'elixir'.  Use :messages / see above for error details.
[deoplete] Too many errors from "alchemist". This source is disabled until Neovim is restarted.
```
This is inside Phoenix Project.
I'm using Arch Linux.

1. Elixir/OTP/Python version

Elixir: 1.8.1

OTP: 21

Python: 3.7:4

2. Are you using VIM or Neovim? Please provide the version.
neovim v. 0.4.2
neovim-qt 0.2.14-1

3. Which pluging are you using:

[ ] basic omnifunc
[ ] YouCompleteMe
[x] deoplete

4. Which steps of Debugging passed?

[ ] Elixir Module definition
first request: error:Socket is not available.%
second: passed
[x] Elixir Function definition
[x] Elixir Module/Function docs
[ ] Your Project Module definition
definition_not_found%
[ ] Your Project Function definition
definition_not_found%

5. Do you have a specific setup? Like Docker and etc
no

When I try to use go_to definition I get:
E426: tag not found: function.
even after running mix.compile

**Comment by slashmili** [comment]
Looks like `elixir` is not in `neovim-qt` $PATH.
You can conform it by running this in vim's command mode:
```
echo $PATH
```

If this is the case, you can either fix the paths in $PATH(not sure how it works in `neovim-qt`) or `ls` elixir binary in one of your current $PATH

**Comment by slashmili** [comment]
I close this thread du to inactivity, feel free to reopen it when you gather more information about your PATH environment value
