### ISSUE TITLE
Autocomplete not works on Windows

### ISSUE THREAD

**Issue by viastakhov** [slashmili/alchemist.vim#168]
Autocomplete not works on Windows, but there is no problem when I use same .vimrc file on Debian 10.

1. Elixir/OTP/Python version
Elixir: Elixir 1.10.2
OTP: Erlang/OTP 21 [erts-10.3] [64-bit]
Python: Python 3.8.2

2. VIM: vim for Windows, ver: 8.2.0628

3. Which pluging are you using:
[X] basic omnifunc
[  ] YouCompleteMe
[  ] deoplete

4. Which steps of Debugging passed?
Debuggins steps was skipped due to steps are not adapted for Windows.

5. Do you have a specific setup? Like Docker and etc
No.

**Comment by slashmili** [comment]
Hi @viastakhov,

I'd assume there is something wrong with the directories or the executing path([e.g](https://github.com/slashmili/alchemist.vim/blob/master/elixir_sense_client#L1)).

I don't have any Windows to debug it :(. I'll keep this issue open in case someone would like to work on this project and make it work in Windows

**Comment by viastakhov** [comment]
There are several problems:
- Directories/path are not correct for Windows;
- There is unix socks being used rather than tcpip for communicating with Elixir Sense server. 
   On my Windows machine unix socks not work.
I tried to fix these issues but no success - autocompletion worked but erl.exe (Elixir Sense) process comsumed a lot of memory with memory leakage~ + 10 MB/sec even if I close vim application.

From my point of view there is huge redesign needed for Windows platform support, so I have decided to start my own plugin development from scratch. to support Windows platform

**Comment by slashmili** [comment]
> Directories/path are not correct for Windows;

That's an easy fix!

> There is unix socks being used rather than tcpip for communicating with Elixir Sense server.

Elixir Sense does support tcpip and supporting it would be simple but time consuming

> even if I close vim application.

The background process stops after [600 seconds ](https://github.com/slashmili/alchemist.vim/blob/master/elixir_sense/lib/self_destruct_timer.ex#L4)

> From my point of view there is huge redesign needed for Windows platform support, so I have decided to start my own plugin development from scratch. to support Windows platform

Sweet!

BTW I'd also recommend to take a look at https://github.com/elixir-lsp/elixir-ls. Setting up vim-lsp module is an alternative approach.
