### ISSUE TITLE
Credo support

### ISSUE THREAD

**Issue by slashmili** [slashmili/alchemist.vim#20]
```
mix credo --format flycheck <filename>
```

We can show the result in `Quickfix` window

**Comment by aerosol** [comment]
That could be done with [Neomake](https://github.com/benekastah/neomake). Does the whole functionality have to be part of `alchemist.vim`?

**Comment by slashmili** [comment]
That's the idea, however not everybody is using NeoVim. The idea is to use Neomake if it's available otherwise handle it in old fashion look at PR  #31

**Comment by aerosol** [comment]
@slashmili neomake supports vim

**Comment by slashmili** [comment]
@c-brenn what do you think?

I know that you faced some problem with `Neomake`, probably you can create a PR for them and fix it there and we shouldn't need this feature

**Comment by c-brenn** [comment]
Yeah I think opening  PR for Neomake (and maybe Syntastic - as I think it is the most popular for Vim users) is a better approach than adding the functionality here

**Comment by slashmili** [comment]
Ok, thanks

**Comment by aerosol** [comment]
Great job guys :) :dancers:
