### ISSUE TITLE
Incompatible with YouCompleteMe ?

### ISSUE THREAD

**Issue by larrylv** [slashmili/alchemist.vim#33]
Not sure if this happened to other folks using both `YouCompleteMe.vim` and `alchemist.vim`, but YCM complained this to me when pressing `List.`:

> Omnifunc returned bad value to YCM! Omnifunc did not return a list or a dict with a "words"  list when expected.

![screen shot 2016-04-14 at 4 37 20 pm](https://cloud.githubusercontent.com/assets/531650/14522032/380a06b4-025f-11e6-8aa3-14b527502c84.png)

Plugin list:

```
Plug 'vim-ruby/vim-ruby'
Plug 'elixir-lang/vim-elixir'
Plug 'slashmili/alchemist.vim'
Plug 'vim-erlang/vim-erlang-runtime'
Plug 'vim-erlang/vim-erlang-compiler'
Plug 'vim-erlang/vim-erlang-omnicomplete'
Plug 'vim-erlang/vim-erlang-tags'
Plug 'ten0s/syntaxerl'
Plug 'pangloss/vim-javascript'
Plug 'elmcast/elm-vim'
Plug 'mustache/vim-mustache-handlebars'
Plug 'fatih/vim-go'
Plug 'guns/vim-clojure-static'
Plug 'kchmck/vim-coffee-script'
Plug 'mxw/vim-jsx'
Plug 'othree/html5.vim'
Plug 'hail2u/vim-css3-syntax'
Plug 'groenewege/vim-less'
Plug 'larrylv/ShowMarks'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'ivalkeen/vim-ctrlp-tjump'
Plug 'tpope/vim-ragtag'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-obsession'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-markdown'
Plug 'tpope/vim-speeddating'
Plug 'tpope/vim-abolish'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-haml'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-vinegar'
Plug 'tpope/vim-rbenv'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-projectionist'
Plug 'tpope/vim-rsi'
Plug 'Valloric/YouCompleteMe' ", { 'do': './install.py --clang-completer' }
Plug 'SirVer/ultisnips'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/syntastic'
Plug 'tomtom/tcomment_vim'
Plug 'skalnik/vim-vroom'
Plug 'honza/vim-snippets'
Plug 'janko-m/vim-test'
Plug 'terryma/vim-multiple-cursors'
Plug 'mileszs/ack.vim'
Plug 'itchyny/lightline.vim'
Plug 'godlygeek/tabular'
Plug 'tudorprodan/html_annoyance.vim'
Plug 'majutsushi/tagbar'
Plug 'airblade/vim-gitgutter'
Plug 'ervandew/supertab'
Plug 'kana/vim-textobj-user'
Plug 'nelstrom/vim-textobj-rubyblock'
Plug 'jwhitley/vim-colors-solarized'
Plug 'Raimondi/delimitMate'
Plug 'mattn/webapi-vim'
Plug 'mattn/gist-vim'
Plug 'benmills/vimux'
Plug 'eapache/rainbow_parentheses.vim'
Plug 'jlanzarotta/bufexplorer'
Plug 'vim-scripts/matchit.zip'
Plug 'vim-scripts/BufOnly.vim'
Plug 'thinca/vim-ref'
Plug 'mhinz/vim-startify'
Plug 'powerman/vim-plugin-AnsiEsc'

```

By the way, thanks for this plugin, it's super useful for Elixir development!

**Comment by larrylv** [comment]
My vim version:

```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 13 2016 18:25:04)
MacOS X (unix) version
Included patches: 1-1724
Compiled by Homebrew
```

**Comment by slashmili** [comment]
Hi,

I'm trying to setup a vim environment with all of your plugins. I'll let you know if I find anything

**Comment by slashmili** [comment]
Can you try this in your box:

```
echo 'COMPX { "List.", [ context: Elixir, imports: [], aliases: []] }' | ~/.vim/bundle/alchemist.vim/alchemist_client -d <your_elixir_project_dir>

```

Make sure to replace <your_elixir_project_dir> with your project directory path and give me the result

**Comment by larrylv** [comment]
@slashmili 

```
$ echo 'COMPX { "List.", [ context: Elixir, imports: [], aliases: []] }' | ~/.vim/bundle/alchemist.vim/alchemist_client -d ~/Code/Hacks/plug

kind:m, word:List., abbr:List.
kind:m, word:List.Chars., abbr:Chars
kind:f, word:List.first, abbr:first/1
kind:f, word:List.last, abbr:last/1
kind:f, word:List.to_atom, abbr:to_atom/1
kind:f, word:List.to_existing_atom, abbr:to_existing_atom/1
kind:f, word:List.to_float, abbr:to_float/1
kind:f, word:List.to_string, abbr:to_string/1
kind:f, word:List.to_tuple, abbr:to_tuple/1
kind:f, word:List.wrap, abbr:wrap/1
kind:f, word:List.zip, abbr:zip/1
kind:f, word:List.delete, abbr:delete/2
kind:f, word:List.delete_at, abbr:delete_at/2
kind:f, word:List.duplicate, abbr:duplicate/2
kind:f, word:List.keysort, abbr:keysort/2
kind:f, word:List.flatten, abbr:flatten/1
kind:f, word:List.flatten, abbr:flatten/2
kind:f, word:List.to_integer, abbr:to_integer/1
kind:f, word:List.to_integer, abbr:to_integer/2
kind:f, word:List.foldl, abbr:foldl/3
kind:f, word:List.foldr, abbr:foldr/3
kind:f, word:List.insert_at, abbr:insert_at/3
kind:f, word:List.keydelete, abbr:keydelete/3
kind:f, word:List.keymember?, abbr:keymember?/3
kind:f, word:List.keytake, abbr:keytake/3
kind:f, word:List.replace_at, abbr:replace_at/3
kind:f, word:List.update_at, abbr:update_at/3
kind:f, word:List.keyfind, abbr:keyfind/4
kind:f, word:List.keyreplace, abbr:keyreplace/4
kind:f, word:List.keystore, abbr:keystore/4
END-OF-COMPX
```

**Comment by larrylv** [comment]
Here is my full vimrc incase it will help: https://github.com/larrylv/dotfiles/blob/3ede8ac60a2707efb9a6c083ddcad8cffbfa3dd0/vimrc

**Comment by slashmili** [comment]
So far the problem that I found is argument to [s:build_completions](https://github.com/slashmili/alchemist.vim/blob/master/autoload/elixircomplete.vim#L59) is empty string.

I'm looking into that to find the reason

**Comment by larrylv** [comment]
Thanks for the update.

**Comment by larrylv** [comment]
Just an FYI: after typing `List.`, I pressed `<C-x><C-o>` and the completion list popped up.

**Comment by slashmili** [comment]
I tested `alchemist.vim` and `YouCompleteMe` with minimum vim settings works fine : 

https://asciinema.org/a/e248rtwzpqihkx7q35bv1oopj

I'm not sure what goes wrong when I run vim with your `.vimrc`.

I'll update you if I find the problem

**Comment by larrylv** [comment]
@slashmili I tried this vimrc and the problem still existed:

```
call plug#begin('~/.vim/bundle')

Plug 'Valloric/YouCompleteMe' ", { 'do': './install.py --clang-completer' }
Plug 'elixir-lang/vim-elixir',              { 'for': ['elixir', 'eelixir'] }
Plug 'slashmili/alchemist.vim',             { 'for': ['elixir', 'eelixir'] }
Plug 'jwhitley/vim-colors-solarized'

call plug#end()

set nocompatible
set t_Co=256
syntax on
let g:solarized_termtrans = 1
let g:solarized_termcolors = 256
let g:solarized_visibility = "high"
let g:solarized_contrast = "high"
set background=dark
colorscheme solarized
```

I have to manually type `C-x C-o` to trigger the completion pop menu.

**Comment by slashmili** [comment]
Your config works for me if I enable filetype plugin

```
filetype plugin on
```

Can you try it and see if it works for you?

**Comment by larrylv** [comment]
@slashmili `:filetype` shows this:

```
filetype detection:ON  plugin:ON  indent:ON
```

I think it's already enabled.

Is vim version related? Here is the full output of `vim --version`:

```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 13 2016 18:25:04)
MacOS X (unix) version
Included patches: 1-1724
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-balloon_eval    +float           +mouse_urxvt     +tcl
-browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         -gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
-clientserver    +iconv           +packages        -toolbar
+clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             +perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      +lua             +rightleft       +writebackup
+diff            +menu            +ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xsmp
+emacs_tags      -mouseshape      +startuptime     -xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        -mouse_gpm       -sun_workshop    -xpm
+extra_search    -mouse_jsbterm   +syntax
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -F/usr/local/Frameworks -DMACOS_X_UNIX  -Os -w -pipe -march=native -mmacosx-version-min=10.11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: /usr/bin/clang   -L. -L/Users/Larry/.rbenv/versions/2.3.0/lib  -fstack-protector -L/usr/local/lib -L/usr/local/lib -F/usr/local/Frameworks -Wl,-headerpad_max_install_names -o vim        -lm  -lncurses -liconv -framework Cocoa  -L/usr/local/lib -llua -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -F/usr/local/Cellar/python/2.7.11/Frameworks -framework Python  -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -lruby-static -framework CoreFoundation -lobjc -L/Users/Larry/.rbenv/versions/2.3.0/lib
```

**Comment by slashmili** [comment]
I tried in Debian:

```
[11:35:27]> vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 31 2015 23:35:24)
Included patches: 1-488, 576
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by jamessan@debian.org
```

Now in Mac with that simplified vim setting doesn't work :(

There is no error though, it's just doesn't open autocomplete menu

**Comment by larrylv** [comment]
@slashmili Actually, if you `set :noshowmode`, it will display the error. The error doesn't show because of the showmode is in the status line.

**Comment by larrylv** [comment]
I tried in Ubuntu, not working for me 😢  :

``` bash
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May 12 2015 21:46:00)
Compiled by vagrant@vagrant
```

The error show like this: `Pattern not found`.

And in Mac with simplified vim, if you `set :noshowmode`, I think the error will show up.

**Comment by slashmili** [comment]
Just noticed forcing `YouCompleteMe` autocompletion with `<C-Space>` works!

Look at https://github.com/Valloric/YouCompleteMe/issues/560 and https://github.com/Valloric/YouCompleteMe/issues/438 for more explanation

**Comment by larrylv** [comment]
@slashmili I read the issues you provided and dig into YCM about this. Actually, `<C-Space>` is required if you didn't provide any semantic triggers for the filetype (taking the issues as an example, clojure). But for elixir, it has semantic triggers by default, which is '.'.  https://github.com/Valloric/YouCompleteMe#the-gycm_semantic_triggers-option

I spent some time on debugging this issue, but still not able to find out why the query sent to aclchemist.vim is empty.

If I manually changed the `request_data['query']` to `List` https://github.com/Valloric/YouCompleteMe/blob/7f419101feb01f32bc1595798291e9cd5143948b/python/ycm/omni_completer.py#L87, it worked just fine.

The query got wrapped in the request_data in `third_party/ycmd/ycmd/request_wrap.py` file (not in the codebase, but installed after compiling), but I'm wondering it's never called/used to create the OmniCompletionRequest. It was used here: https://github.com/Valloric/YouCompleteMe/blob/7f419101feb01f32bc1595798291e9cd5143948b/python/ycm/youcompleteme.py#L192

Maybe you could help from here? I'm not a vim expert, and I don't know how to debug in python vim plugins.

Thank you so much for spending time on this issue.

---

UPDATE:

the `request_data` looks like this:

```
{
  'line_value': '  List.',
  'start_column': 8,
  'column_num': 8,
  'query': '',
  'filetypes': ['elixir']
}
```

So the problem is `start_column` is wrong.

**Comment by larrylv** [comment]
The reason `<C-Space>` works is this https://github.com/Valloric/YouCompleteMe/blob/7f419101feb01f32bc1595798291e9cd5143948b/autoload/youcompleteme.vim#L225-L236 YCM maps `<C-Space>` to `<C-X><C-O><C-P>` to trigger omni completion

**Comment by larrylv** [comment]
Finally found the cause why the `start_column` value is wrong.

ycmd will use this [REGEX](https://github.com/Valloric/ycmd/blob/bc323738c6c07efb707b5d7d06488d270d3140f8/ycmd/identifier_utils.py#L53) `re.compile( r"[_a-zA-Z]\w*", re.UNICODE )` to match an identifier, and traversing the index to find out the start column of the identifier.

But for my case: `List.`,  since there is a trailing `.`, it won't match, so it will just return the end column number, which makes the calculation of `query` is empty.

The quick fix will be updating `DEFAULT_IDENTIFIER_REGEX` in `third_party/ycmd/ycmd/identifier_utils.py` to:

``` diff
diff --git a/ycmd/identifier_utils.py b/ycmd/identifier_utils.py
index 28f39f3..92f8371 100644
--- a/ycmd/identifier_utils.py
+++ b/ycmd/identifier_utils.py
@@ -50,7 +50,7 @@ COMMENT_AND_STRING_REGEX = re.compile(
   #  3. the escaped double quote inside the string
   r'(?<!\\)"(?:\\\\|\\"|.)*?"', re.MULTILINE )

-DEFAULT_IDENTIFIER_REGEX = re.compile( r"[_a-zA-Z]\w*", re.UNICODE )
+DEFAULT_IDENTIFIER_REGEX = re.compile( r"[_a-zA-Z][\w\.]*", re.UNICODE )

 FILETYPE_TO_IDENTIFIER_REGEX = {
     # Spec: http://www.w3.org/TR/CSS2/syndata.html#characters
```

And I wonder why this works vim-ruby, it turns out in `vim-ruby` plugin, it will parse and get the current `query` it self: https://github.com/vim-ruby/vim-ruby/blob/666adb5bcdfb2d21572a58fcdf7545a26bac32a0/autoload/rubycomplete.vim#L606

Apparently my changes for YCM is just a temporary workaround, and you may consider doing the same thing as `vim-ruby` plugin does, which is instead of justing using the `base_or_suggestions` parameter passed by YCM, also parsing to get the query in plugin itself.

Thanks for your time.

**Comment by larrylv** [comment]
Created a vim plugin to deal with this: https://github.com/larrylv/ycm-elixir In case of anyone else coming into this issue.

**Comment by slashmili** [comment]
Thank! I'll take look at your suggestion this weekend

**Comment by Elinos** [comment]
Hi, I got the same error.
This is what I get when I run `cho 'COMPX { "List.", [ context: Elixir, imports: [], aliases: []] }' | ~/.vim/bundle/alchemist.vim/alchemist_client -d .`
```
Traceback (most recent call last):
  File "/Users/ktsarnakliyski/.vim/bundle/alchemist.vim/alchemist_client", line 77, in <module>
    main(sys.argv[1:])
  File "/Users/ktsarnakliyski/.vim/bundle/alchemist.vim/alchemist_client", line 69, in main
    print(a.process_command(cmd), end="")
  File "/Users/ktsarnakliyski/Library/Mobile Documents/com~apple~CloudDocs/Mackup/.vim/bundle/alchemist.vim/alchemist.py", line 48, in process_command
    sock = self._connect(connection)
  File "/Users/ktsarnakliyski/Library/Mobile Documents/com~apple~CloudDocs/Mackup/.vim/bundle/alchemist.vim/alchemist.py", line 125, in _connect
    sock.connect(host_port)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
TypeError: getsockaddrarg: AF_INET address must be tuple, not NoneType
```
I have no clue what to do about it :)

**Comment by slashmili** [comment]
@Elinos the way that this plugin works is, it runs alchemist-server on localhost and a random port and logs out the port [into a file](https://github.com/slashmili/alchemist.vim/blob/master/alchemist.py#L100)

Next time if you run a command it uses the existing instance and get the data out.

Based on the log, I can say that the plugin found the file and opened it, tries to parse but it couldn't find the `<localhost:port>` line in that file.

Try to find out the file path and see what's inside that file. you can do that by printing [log_file](https://github.com/slashmili/alchemist.vim/blob/master/alchemist.py#L113) variable in line 113

**Comment by Elinos** [comment]
@slashmili So what I found out is this:
I've added this line to alchemist.py - `print(log_file)` and this is the result:
`<open file '/var/folders/v1/9cf15p1j5pb3lkw0zdq28swr0000gn/T/alchemist_server/zSUserszSktsarnakliyskizSProgrammingzSPlaygroundzSExercismzSelixirzSbob', mode 'w' at 0x10227bc00>`

Then I printed what's inside this file(zSUserszSktsarnakliyskizSProgrammingzSPlaygroundzSExercismzSelixirzSbob) and this came out:
`No file named /Users/ktsarnakliyski/Library/Mobile`

Any suggestions?

PS: A little update:
- I was using [mackup](https://github.com/lra/mackup) to sync my app configurations and I guess for some reason the script didn't find the full path to the file(iCloud folder).
- So I uninstalled it to test
- It still doesn't work as expected but this is the file contents now:
```
warning: module attribute @docmodule was set but never used
  /Users/ktsarnakliyski/.yadr/vim/bundle/alchemist.vim/alchemist-server/lib/helpers/capture_io.exs:3

warning: variable "all_loaded" does not exist and is being expanded to "all_loaded()", please use parentheses to remove the ambiguity or change the variable name
  /Users/ktsarnakliyski/.yadr/vim/bundle/alchemist.vim/alchemist-server/lib/helpers/process_commands.exs:15

warning: variable "read_line" does not exist and is being expanded to "read_line()", please use parentheses to remove the ambiguity or change the variable name
  /Users/ktsarnakliyski/.yadr/vim/bundle/alchemist.vim/alchemist-server/lib/server/io.exs:21

warning: variable "schedule_tick" does not exist and is being expanded to "schedule_tick()", please use parentheses to remove the ambiguity or change the variable name
  /Users/ktsarnakliyski/.yadr/vim/bundle/alchemist.vim/alchemist-server/lib/self_destruct_timer.ex:5

warning: variable "idle_expired" does not exist and is being expanded to "idle_expired()", please use parentheses to remove the ambiguity or change the variable name
  /Users/ktsarnakliyski/.yadr/vim/bundle/alchemist.vim/alchemist-server/lib/self_destruct_timer.ex:11

warning: variable "destroy" does not exist and is being expanded to "destroy()", please use parentheses to remove the ambiguity or change the variable name
  /Users/ktsarnakliyski/.yadr/vim/bundle/alchemist.vim/alchemist-server/lib/self_destruct_timer.ex:12

warning: variable "schedule_tick" does not exist and is being expanded to "schedule_tick()", please use parentheses to remove the ambiguity or change the variable name
  /Users/ktsarnakliyski/.yadr/vim/bundle/alchemist.vim/alchemist-server/lib/self_destruct_timer.ex:13

warning: variable "now" does not exist and is being expanded to "now()", please use parentheses to remove the ambiguity or change the variable name
  /Users/ktsarnakliyski/.yadr/vim/bundle/alchemist.vim/alchemist-server/lib/self_destruct_timer.ex:18

warning: variable "now" does not exist and is being expanded to "now()", please use parentheses to remove the ambiguity or change the variable name
  /Users/ktsarnakliyski/.yadr/vim/bundle/alchemist.vim/alchemist-server/lib/self_destruct_timer.ex:30

warning: variable "last_request" does not exist and is being expanded to "last_request()", please use parentheses to remove the ambiguity or change the variable name
  /Users/ktsarnakliyski/.yadr/vim/bundle/alchemist.vim/alchemist-server/lib/self_destruct_timer.ex:30

warning: variable "idle_time" does not exist and is being expanded to "idle_time()", please use parentheses to remove the ambiguity or change the variable name
  /Users/ktsarnakliyski/.yadr/vim/bundle/alchemist.vim/alchemist-server/lib/self_destruct_timer.ex:33

warning: variable "timeout" does not exist and is being expanded to "timeout()", please use parentheses to remove the ambiguity or change the variable name
  /Users/ktsarnakliyski/.yadr/vim/bundle/alchemist.vim/alchemist-server/lib/self_destruct_timer.ex:33

warning: module attribute @version was set but never used
  /Users/ktsarnakliyski/.yadr/vim/bundle/alchemist.vim/alchemist-server/lib/server.exs:6

ok|localhost:61331
```

I guess this is because I have elixir [1.4.0](https://elixirforum.com/t/iex-zero-arity-functions-elixir-1-4/3182) installed?

**Comment by slashmili** [comment]
Yes the warnings are because of Elixir 1.4.0 but the client is supposed to [read all lines and find the match](https://github.com/slashmili/alchemist.vim/blob/master/alchemist.py#L296)

I have the same data in that file but still the last line match and it returns the host and the port

Can you print out the `connection` value and see if it works?

I used your output and saved it under `/tmp/elinos.txt`, tried it with this python script and it returns the correct value:
```
In [3]: from alchemist import AlchemistClient

In [4]: alchemist = AlchemistClient()

In [5]: server_log = "/tmp/elinos.txt"

In [6]: print(alchemist._extract_connection_settings(server_log))
('localhost', 61331)
```

**Comment by Elinos** [comment]
Strange...now it works :D without any change...
Thanks :)

**Comment by slashmili** [comment]
@larrylv / @Elinos  can you try [elixir-sense](https://github.com/slashmili/alchemist.vim/tree/elixir-sense) branch?

**Comment by larrylv** [comment]
@slashmili I just tried, it works for me! Thanks!
