### ISSUE TITLE
NameError: name 'raw_input' is not defined

### ISSUE THREAD

**Issue by mad01** [slashmili/alchemist.vim#34]
OS X, Python 2.7.11
got this when using K to get ExDoc on function

```
Traceback (most recent call last):
  File "/Users/alexander/.vim/plugged/alchemist.vim/after/../alchemist_client", line 79, in <module>
    main(sys.argv[1:])
  File "/Users/alexander/.vim/plugged/alchemist.vim/after/../alchemist_client", line 58, in main
    cmd = raw_input()
NameError: name 'raw_input' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alexander/.vim/plugged/alchemist.vim/after/../alchemist_client", line 81, in <module>
    print("error: %s" % e.message)
```

**Comment by slashmili** [comment]
Looks like in your environment `/usr/bin/env python` is pointed to [python 3](http://stackoverflow.com/a/21122817/683247)

I'll try to make it python 3 compatible

**Comment by slashmili** [comment]
Please update with the latest changes :tada:

**Comment by mad01** [comment]
Cool updated works grate \o/

**Comment by herambkulkarni1** [comment]
class StackOverflowUser:
        def __init__(self, name, userid, rep): 
            self.name = name
            self.userid = userid
            self.rep = rep

 name = raw_input("Enter name: ")
 userid = int(raw_input("Enter user id: "))
 rep = int(raw_input("Enter rep: "))

 dave = StackOverflowUser(name, userid, rep)

error: raw input is not defined 
pls solve this error..........

**Comment by herambkulkarni1** [comment]
class User:
        def __init__(self, name, userid, rep): 
            self.name = name
            self.userid = userid
            self.rep = rep

 name = raw_input("Enter name: ")
 userid = int(raw_input("Enter user id: "))
 rep = int(raw_input("Enter rep: "))

 dave = User(name, userid, rep)

**Comment by herambkulkarni1** [comment]
showing raw_input is not defined 
pls solve this error...........................

**Comment by slashmili** [comment]
@herambkulkarni1 I don't think you are using `alchemist.vim`, it's a plugin for Elixir and your example doesn't look like an Elixir code

**Comment by Thecollectivecode** [comment]
> showing raw_input is not defined
> pls solve this error...........................

have you solved your error???
if not then,
sir i am thinking you are using python 3.5 or something, here you have to use only input instead of raw_input, thats it...
