### ISSUE TITLE
Can I use alchemist with neocomplete to autocomplete?

### ISSUE THREAD

**Issue by Cifer-Y** [slashmili/alchemist.vim#38]
Hi, I'm not very good at vim, I need help or guide.
I want to complete code without typing <C-X><C-O>,
and I'm using neocomplete for autocomplete.
So may I request your help for guiding me how to do that?

**Comment by slashmili** [comment]
Unfortunately I'm not familiar with  `neocomplete` and couldn't even make it work for normal autocomplete based on their github page.

I'd suggest that you ask in stackoverflow about setting up `neocomplete`.

If you use _alchemist.vim_, you can always use `<C-x><C-o>` to open the autocomplete menu.

**Comment by ecly** [comment]
If anyone has actually got it working with neocomplete since this, I'd love to hear. Otherwise I'll take that advice and throw this over to Stackoverflow. Funny that there should be such difference, as the supported deoplete is made by the same guy who made neocomplete.
