### ISSUE TITLE
Autocomplete issue in Mix projects.

### ISSUE THREAD

**Issue by nayzak** [slashmili/alchemist.vim#44]
I don't know if there a bug in alchemist.vim plugin or this is an expected behavior of vim, however I found this issue using this plugin. Shortly, when I launch vim and execute :cd into my project, then autocomplete for Elexir stdlib works fine, but it doesn't work for my project modules and it dependencies. When I launch vim from project directory then everything works fine.

**Comment by nayzak** [comment]
I found the root of my problem in `alchemist#alchemist_client()` function. It uses global variable `g:alchemist#root` which sets ones on plugin launch with result of `getcwd()` call. When I change `CWD` by executing `:cd` `g:alchemist#root` does not change.

**Comment by slashmili** [comment]
Hi, sorry for late reply. I was traveling past few days.

To be honest I'm not sure how can I help. There was a reason that I used `getcwd` once and keep it for the rest of session.

Do you have any suggestion?

**Comment by nayzak** [comment]
I can understand why you did so. And if nobody complained on this stuff, than it's ok.
One way is to make option that will tell plugin that `cwd` is always pointing to `mix` project root. However it would be silly. Another option is to check existence of `mix.exs` in `cwd` each time `alchemist#alchemist_client()` is called. And if it's not there, than try to find it in root directories. Again it's rather strange solution. But it's possible to cache `cwd` and check if it was changed on `alchemist#alchemist_client()` call, if it was changed than try to find the right path for the `mix` project.
