### ISSUE TITLE
implement xref

### ISSUE THREAD

**Issue by slashmili** [slashmili/alchemist.vim#51]
The idea is to use xref to find the places that a given module/function is used and helps users to refactor a code!

alchemist-server doesn't support xref yet, need to implement the base there first.

it should work like this:

```
:ExRef MyApp.Repo -> open a window that list of files that uses this module
:ExRef MyApp.User.changeset -> open a window that list of files that uses this function
```

**Comment by slashmili** [comment]
```
mix xref callers MyApp.User
```

```
Mix.Tasks.Compile.Elixir.manifests
|> Mix.Compilers.Elixir.read_manifest("")
```

Look at [xref implementation in mix](https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/xref.ex)

**Comment by hauleth** [comment]
Why not leave it to user via `:make` (or any other asynchronous part) calls?

**Comment by slashmili** [comment]
@hauleth the idea was to have list of something like this

![screen shot 2017-11-14 at 11 07 07](https://user-images.githubusercontent.com/585764/32774254-019c1924-c92c-11e7-972a-fc09828c8558.png)

Anyway since it wouldn't work in umbrella project we are going to call it off

**Comment by hauleth** [comment]
@slashmili that is exactly what `:make` would provide you via quickfix or `:lmake` via location list. The only problem is to have mapping for that. [I have created quick and dirty function for that](https://github.com/hauleth/dotfiles/blob/3057029070295f928baf89d63d402ec4c105b1d2/nvim/autoload/ft/elixir.vim) but they still need some work. [Example usage can be seen there](https://github.com/hauleth/dotfiles/blob/8755edd3ac5e286f760ce2f75adf34b13f5dd1ca/nvim/after/ftplugin/elixir.vim#L6).

This still doesn't work with umbrella though.
