### ISSUE TITLE
Does this work in Windows?

### ISSUE THREAD

**Issue by qwerescape** [slashmili/alchemist.vim#56]
I've been trying to get it to work on Windows for a day now. Being new to Vim doesn't help, but I am noticing some problems such as "/" vs "\" and the alchemist_client file having a shebang which isn't recognized by Windows. 

Is this meant to support Windows?

**Comment by slashmili** [comment]
Hey @qwerescape It's good to know that someone trying to make it work in Windows!

I don't have Windows so I can't test it.

In case you are interested to fix the problem there few components:
- Alchemist-server which runs on Erlang VM, this should work on windows! to try that: 

```
cd alchemist.vim/alchemist-server
make test
```
- Alchemist client:

```
cd alchemist.vim/
python alchemist.py
```

For the path issue in python you can use https://docs.python.org/2/library/os.path.html#os.path.join to build the path that works in any OS 
- Vim Plugin:
  Vim plugin should be universal(!) so should work fine

The only place that I used path in vim plugin is at [after/plugin/alchemist.vim](https://github.com/slashmili/alchemist.vim/blob/master/after/plugin/alchemist.vim#L8)

I don't know if there is any helper for that but worst case you can check for the OS and build different path

**Comment by qwerescape** [comment]
:( sorry, I made a hackintosh out of my pc already...
