### ISSUE TITLE
Homebrew elixir path for Jump to definition

### ISSUE THREAD

**Issue by mikeLspohn** [slashmili/alchemist.vim#57]
Is there anyway to set the path for the jump to definition as stated in the wiki for a Homebrew installed Elixir? I might just be missing something with Homebrew, but it seems that it just keeps the binaries not the source, so I can't figure out how to set the path for this. 

Is there a simple solution for this, or is this something that's not currently implemented?

**Comment by slashmili** [comment]
Hey @mikeLspohn ,

When you install Elixir with brew, it doesn't compile it in your machine, it only downloads the Elixir beam files:

```
iex(1)> i List
Term
  List
Data type
  Atom
Module bytecode
  /usr/local/Cellar/elixir/1.3.3/bin/../lib/elixir/ebin/Elixir.List.beam
Source
  /private/tmp/elixir-20160918-88373-p1jm9j/elixir-1.3.3/lib/elixir/lib/list.ex
Version
  [174162157282339125927796226318859137592]
...
```

So what I do is download the Elixir source code separately and configure the plugin to use that

**Comment by codyjroberts** [comment]
What about the erlang source?  The emacs package seems to have two variables, whereas this only has one.  The elixir source doesn't have an 'otp' folder.

**Comment by slashmili** [comment]
@codyjroberts take a look at https://github.com/slashmili/alchemist.vim/wiki#configs

The `otp` directory is erlang's source which should be a clone of this repo https://github.com/erlang/otp

Just because I was lazy I decided to use one variable :)

Do you have problem with keeping both elixir and otp source like the way that manual is explained?

**Comment by codyjroberts** [comment]
No I can put it into the same dir =).  Thanks!

**Comment by slashmili** [comment]
I close this issue for now, fell free to open it if you think it needs more discussion
