### ISSUE TITLE
Navigate to the definition of a macro imported function

### ISSUE THREAD

**Issue by jonathan-soifer** [slashmili/alchemist.vim#69]
Hi,

Alchemist's "go to definition" for my project's functions/modules work just fine.

But looking at the following piece of code:

```
def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :content, :post_id])
    |> validate_required([:name, :content, :post_id])
end
```

If I press ctrl+] on top of either **"cast"**, **"validate_required"** or **"struct"** I get a `E426: Tag not found`.

Any idea how to fix this?

    MacOS 10.12.1
    ViM 8.0.52
    Elixir 1.3.4

Which Elixir?
`/usr/local/bin/elixir`

Installed using homebrew

**Comment by jaysoifer** [comment]
With the help from a user in the Elixir Forum I was able to find out that this is probably related to me moving my project around within my computer's directory structure.

Is there any way I can update those references to my current folder? Where does alchemist gets them?

**Comment by slashmili** [comment]
Hi,

As annoying as it is, autocomplete doesn't work for `validate_required` and other functions that are added to a module by `use` macro :(

`struct` is a function argument so it won't work on that

/cc @carloslima this also interesting thing to fix :D [atom-elixir ](https://github.com/msaraiva/atom-elixir) has some patch on `alchemist-server` that make it possible

**Comment by jonathan-soifer** [comment]
Oops! Sorry about the "struct". I was just trying to go into whichever definitions I could.

After a few hours trying to debug this, it gets fuzzy 😞 

I actually fixed my project by running `mix deps.get` and `npm install` again.

Should I close this? Or are you going further into the _use_ macro subject?

**Comment by slashmili** [comment]
Let's see what can we do about macro imported functions. It would be great to jump to those.

**Comment by slashmili** [comment]
@jaysoifer  

FYI I am working on [elixir-sense](https://github.com/slashmili/alchemist.vim/tree/elixir-sense) integration which allows to get more information about micro imported function. it's still beta but you can give it a try :)

**Comment by jonathan-soifer** [comment]
Thanks for the heads-up!

I've been assigned to deal with some Frontend issues (Javascript! Yey!) but I think I will have some time to try it out next weekend.

**Comment by slashmili** [comment]
@jaysoifer please try the new version
