### ISSUE TITLE
Dumb completion, did I forget something ?

### ISSUE THREAD

**Issue by sysblade** [slashmili/alchemist.vim#73]
Hello,

I see that my completion with Alchemist and YMC is quite dumb, basically it look like I can see all the possible function for all the modules everywhere, here is a small screenshot that would explain better:

http://s3.kedare.net/issues/Screen+Shot+2016-12-26+at+22.11.43.png

What could cause this ? I suppose this is not expected ?

Thanks.

**Comment by slashmili** [comment]
Hmm, I remember it never worked very well with YMC :(

I just checked the screencast that I recorded long time ago and it is like your screenshot.

**Comment by sysblade** [comment]
What is the recommended way to install it to have an equivalent behavior ? Typically having completion working automatically with OmniCompletion ? (Because for now I can only make it work when using <C-x><C-o>, can it work with tab ?)

**Comment by slashmili** [comment]
@kedare I've seen most of people use it with [deoplete.nvim](https://github.com/Shougo/deoplete.nvim)

**Comment by nhooyr** [comment]
It doesn't seem to complete many functions or modules at all for me. Only completes standard library functions or modules. Have I got my project setup wrong? I created it with `mix phoenix.new`.

**Comment by slashmili** [comment]
@nhooyr So far based on the experience the YMC and alchemist.vim don't play well with each others

**Comment by nhooyr** [comment]
Sorry, forgot to mention I'm using deoplete.

**Comment by uberbrodt** [comment]
I've got the same thing, using latests versions of Alchemist and YCM. One thing that is interesting, is that if you invoke YCM completion directly through <C-Space>, it shows intelligent completions based on the context.

**Comment by slashmili** [comment]
@uberbrodt what do you mean by `invoke YCM completion directly`, do mean invoke YCM completion for alchemist?

**Comment by uberbrodt** [comment]
@slashmili Sorry, should have been more clear. When I say "invoke YCM completion directly", I mean calling the `omnifunc`. Which, is set to  `elixircomplete#Complete` for me.

After spending a bit more time on it, and looking more closely at issue #33, It seems that it's related to the regex that this plugin fixes: https://github.com/larrylv/ycm-elixir. I would say it's not perfect; seems to get confused when trying to complete multiple module names in a chain (ie: `Foo.Bar.` won't have any completions, even though there are other modules under the `Bar` namespace). I'm not sure if that's an Alchemist or a YCM issue though.

**Comment by charleshan** [comment]
I'm getting the same error as well.
`Omnifunc returned bad value to YCM! Omnifunc did not return a list or a dict with a "words"  list when expected.`

**Comment by slashmili** [comment]
@kedare /  @omin thanks for reporting the issue

I'm working on [elixir-sense](https://github.com/slashmili/alchemist.vim/tree/elixir-sense) which solves lots of problem like this.

I keep the issuer open until that new feature is ready

**Comment by slashmili** [comment]
@kedare / @omin please try the new version
