### ISSUE TITLE
Allow to jump through navigation

### ISSUE THREAD

**Issue by uri** [slashmili/alchemist.vim#82]
It would be great if, like in the vim help, you could jump through documentation. For example, if viewing the documentation for `Enum`

```
* Enum

Provides a set of algorithms that enumerate over enumerables according
to the `Enumerable` protocol.

    iex> Enum.map([1, 2, 3], fn(x) -> x * 2 end)
    [2, 4, 6]
```

It would be great if can put your cursor on `map` and bring up the `Enum.map` documentation. Currently, using `K`, this does not work as vim attempts to find a `man` entry.

**Comment by slashmili** [comment]
@uri try the merged changes, should fix your problem

**Comment by uri** [comment]
Works great, thanks!
