### ISSUE TITLE
Remote Alchemist Server

### ISSUE THREAD

**Issue by rawkode** [slashmili/alchemist.vim#84]
I run my applications inside Docker containers, which means that `deps` and `_build` aren't available to vim.

Is there a way to run this plugin, but ask it to speak to another alchemist server over a socket / port combination?

Thanks

**Comment by slashmili** [comment]
@rawkode you do share a working directory with Docker. Aren't `deps` and `_build` directories automatically created in that shared directory?

**Comment by rawkode** [comment]
@slashmili No, I use local volumes to keep `deps` and `_build` away from my working directory, which is fantastic; until I want code completion :confused: 

Is adding the remote alchemist configuration not something you're likely to support?

**Comment by slashmili** [comment]
@rawkode I couldn't find a proper solution. I can make some changes that it works for your but couldn't find a general solution.

The challenges:

- Every time you start a Docker, you get a new IP address which makes it hard to configure one IP/port in vim config
- People usually have multiple projects and not sure how can we have multiple ip/port config per mix project

**Comment by rawkode** [comment]
So each of my Elixir projects runs their own alchemist, through `docker-compose`, with the following:

```
  alchemist-server:
    image: rawkode/elixir-alchemist-server:latest
    ports:
      - 50501:50501
    volumes_from:
      - application
```

So if I can configure this plugin to connect to `localhost:50501`, then no matter what project I am editing, it should work. Obviously if I am working on multiple projects at the same time, then it's not going to work. Is this a common use-case though?

**Comment by slashmili** [comment]
@rawkode check out the new changes in #78 

I hope it helps you to setup your project in docket
