### ISSUE TITLE
weird module completion

### ISSUE THREAD

**Issue by nhooyr** [slashmili/alchemist.vim#88]
In a phoenix project with the following controller:
```elixir
defmodule HelloPhoenix.PageController do
  use HelloPhoenix.Web, :controller

  def index(conn, _params) do
    conn
    |> put_layout("admin.html")
    |> render("index.html")
  end

  def somefoo() do
  end
end
```

If I try and complete a module name, I get: https://asciinema.org/a/disrxp5hcg4hqnit8o4kjk6kc

Why do the completion options not have the full prefix? if I am completing `HelloPhoenix.Endpoint`, shouldn't the option in the completion menu also be `HelloPhoenix.Endpoint`? Not just `Endpoint`? Is there any way to fix this?

**Comment by slashmili** [comment]
@nhooyr I guess it's just mater of taste!

This is an example of Android Studio:

![screen shot 2017-02-23 at 10 14 45 2](https://cloud.githubusercontent.com/assets/585764/23252402/00223d4e-f9b1-11e6-92bc-12c80466a3ca.png)

And this is an example from XCode:

![screen shot 2017-02-23 at 10 17 49 2](https://cloud.githubusercontent.com/assets/585764/23252508/5d0f7940-f9b1-11e6-8954-c98aa2da6677.png)

**Comment by nhooyr** [comment]
I'm fine with the way xcode or android studio do it. It's just that alchemist.vim is showing me `HelloPhoenix.` in the first completion option, but not in any of the rest, even though they include completing it. They should be `HelloPhoenix.ModuleName`. not just `ModuleName` as I don't even have `HelloPhoenix` yet.

**Comment by slashmili** [comment]
Sorry @nhooyr I'm lost a bit.

Nevertheless, we are using `IEx` autocomplete module, try to check your test case under under iex: `iex -S mix` and try to autocomplete by pressing `tab` and let me know if it behaves differently there.
Would be great to capture your `iex` test case with asciinema as well.

**Comment by nhooyr** [comment]
Right now I'm getting

```
HelloPhoenix.   m
Endpoint        m
ErrorHelpers    m
ErrorView       m
Gettext         m
HelloController m
HelloView       m
LayoutView      m
PageController  m
PageView        m
Repo            m
Router          m
UserSocket      m
Web             m
```

I want

```
HelloPhoenix                 m
HelloPhoenix.Endpoint        m
HelloPhoenix.ErrorHelpers    m
HelloPhoenix.ErrorView       m
HelloPhoenix.Gettext         m
HelloPhoenix.HelloController m
HelloPhoenix.HelloView       m
HelloPhoenix.LayoutView      m
HelloPhoenix.PageController  m
HelloPhoenix.PageView        m
HelloPhoenix.Repo            m
HelloPhoenix.Router          m
HelloPhoenix.UserSocket      m
HelloPhoenix.Web             m
```

**Comment by slashmili** [comment]
When you start typing, you have the base module in your editor and the rest will show up in the suggestion window
like this:
![screen shot 2017-07-23 at 12 05 37](https://user-images.githubusercontent.com/585764/28498502-48bf745e-6f9f-11e7-8844-0538230b39bc.png)

I guess it's better to keep it like that.
