### ISSUE TITLE
`<C-W><C-]>` causes error 'E426: tag not found: Application'

### ISSUE THREAD

**Issue by dylan-chong** [slashmili/alchemist.vim#89]
I assume this is because Alchemist overrides the mapping for `<C-]>` to work, but not `<C-W><C-]>`.

As a side note, I can't get around this problem by using `nnoremap <C-W><C-]> :tab<SPACE>split<CR><C-]>` because that last `<C-]>` doesn't seem to be overriden by Alchemist.

**Comment by slashmili** [comment]
@dylan-chong you can use it like this

```
nnoremap <buffer> <silent> <C-W><C-]> :tab<SPACE>split<CR>:call alchemist#exdef()<CR>
```

Since we are going to use `<C-W>` prefix, what do you think if we split the window and open the file in new window instead of new tab?

**Comment by dylan-chong** [comment]
Oh whoops. I forgot that `<C-W>` was used for window, so I guess `<C-W><C-]>` should open a new window.

Anyway, your remap code still doesn't seem to override the behaviour unless I add `autocmd BufEnter *` at the start of the line. This still isn't a nice solution, since if there was no tag found under the cursor, then you are left with an extra window and an error message (or no error message if you leave out the `<silent>`!)

**Comment by slashmili** [comment]
I close this issuer. Let me know if I can help
