### ISSUE TITLE
ExDef attempts to look up docs on Jose's path

### ISSUE THREAD

**Issue by jc00ke** [slashmili/alchemist.vim#90]
See the asciicast below. I've got 31c13df installed with Neovim `0.2.0-DEV` via `Plug` and both Erlang 19.2 and Elixir 1.4.2 are installed via `asdf` plugins.

[![asciicast](https://asciinema.org/a/107192.png)](https://asciinema.org/a/107192)

@josevalim :wink:

**Comment by josevalim** [comment]
If you are using precompiled Elixir, it is compiled on my machine or another machine, so that will happen. :)

**Comment by jc00ke** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10214012-118866928_7-s1-v1.png?transparent=1&palette=1&width=246)

I kid I kid.

So, no way around this besides compiling Elixir myself I assume?

**Comment by slashmili** [comment]
@jc00ke There is a workaround, take a look at [Jump to definition](https://github.com/slashmili/alchemist.vim/wiki#jump-to-definition) configs

**Comment by jc00ke** [comment]
@slashmili are you referring to setting `g:alchemist#elixir_erlang_src` or `<C-]>`?

**Comment by slashmili** [comment]
@jc00ke I'm referring to `g:alchemist#elixir_erlang_src`

If [the source file path contain `/elixir/` or `/otp/`](https://github.com/slashmili/alchemist.vim/blob/master/alchemist.py#L200) it looks for the source file from configured path in `g:alchemist#elixir_erlang_src`

**Comment by jc00ke** [comment]
Cool, thanks for clarifying.

`asdf` puts things in different directories, so I might need to do some symlinkin' to get this to work.

```
~
⟩ ls .asdf/installs/elixir/
1.3.4/  1.4.0/  1.4.0-rc.1/  1.4.2/

~
⟩ ls .asdf/installs/erlang/
19.1/  19.2/
```

**Comment by slashmili** [comment]
@jc00ke If I'm not wrong `asdf` download the binaries so there is no need to symlink anything.

You should get the source for each language separately and put it on the correct directory

**Comment by jc00ke** [comment]
Great, I'm sorted. Thanks for the help!

**Comment by indera** [comment]
After I setup the path
let g:alchemist#elixir_erlang_src = "/usr/local/share/src"
how do I actually jump to the definition?

Entering "gd" when my cursor is over the "GenServer" goes to the first occurrence in the file, but I expected it to go to the implementation file

**Comment by slashmili** [comment]
@indera  https://github.com/slashmili/alchemist.vim/wiki#jump-to-definition
