### ISSUE TITLE
Make it possible to remap normal-mode `K`

### ISSUE THREAD

**Issue by linduxed** [slashmili/alchemist.vim#91]
Currently there's neither a way to remap the documentation lookup, nor is there a way to disable the addition of the mapping to normal-mode `K`.

I think having either of the two above would be beneficial for people using this plugin that have a non-standard set of mappings.

**Comment by slashmili** [comment]
@linduxed would you mind to implement that? You can follow [g:alchemist_tag_disable](https://github.com/slashmili/alchemist.vim/blob/master/after/ftplugin/elixir.vim#L26) implementation

**Comment by linduxed** [comment]
OK, I'll submit a PR this week and we can continue the discussion there!

**Comment by linduxed** [comment]
Phew, that took a while! A PR is up for this functionality.

Next time I shouldn't be promising a date as to when something will be ready! 😄
