### ISSUE TITLE
Autocomplete not working fully

### ISSUE THREAD

**Issue by konstantinzolotarev** [slashmili/alchemist.vim#93]
There are lot of issues with autocomplete module.
My issue is that omni autocomplete does not show all available methods

For example here is suggestions from vim: 
<img width="526" alt="screen shot 2017-03-20 at 17 19 57" src="https://cloud.githubusercontent.com/assets/286431/24106853/ddaca804-0d91-11e7-9f18-9fab2a70a037.png">

And here is from atom: 
<img width="724" alt="screen shot 2017-03-20 at 17 20 09" src="https://cloud.githubusercontent.com/assets/286431/24106872/e69918d0-0d91-11e7-96e6-f438e216e54b.png">

Any idea what I did wrong ?

**Comment by slashmili** [comment]
@konstantinzolotarev well [atom-elixir](https://github.com/msaraiva/atom-elixir) has customize version of `alchemist-server` which is able to expand macros and show you those.

Unfortunately it's not available yet in this plugin and [alchemist-server](https://github.com/tonini/alchemist-server).

There is an issue in `alchemist-server` https://github.com/tonini/alchemist-server/issues/6 and in `alchemist.vim` https://github.com/slashmili/alchemist.vim/issues/69

I hope that we can have it soon as well :)

**Comment by konstantinzolotarev** [comment]
@slashmili Awesome ! 
Thank you very much for reply and for your work on this plugin.
