### ISSUE TITLE
Use ElixirSense

### ISSUE THREAD

**Issue by slashmili** [slashmili/alchemist.vim#97]
ElixirSense looks promising: https://github.com/msaraiva/elixir_sense

Let's try it!

**Comment by ghost** [comment]
I would love to look at this, I don't know much vimL (seems to be mostly python in implementation though) but am willing to dig in. Can I get any pointers on where to dig in to start?

**Comment by slashmili** [comment]
Hey @colbydehart,

The starting point would be to understand how does `elixir_sense` work and how much is different from `alchemist-server`

I haven't spent time on this issue as well

**Comment by slashmili** [comment]
@colbydehart turns out `elixir_sense` does all the heavy lifting and it's quite simple. However we can only communicate with the server in erlang binary terms. It would be much easier we we could use Elixir client rather than python client to communicate to the server. I checked the time command execution of a simple elixir vs python script:

```
bash-3.2$ time elixir h.exs
hello

real	0m0.399s
user	0m0.348s
sys	0m0.210s

bash-3.2$ time python h.py
hello

real	0m0.035s
user	0m0.022s
sys	0m0.008s
```

Clearly python is winner for that. I [implemented](https://github.com/slashmili/alchemist.vim/blob/elixir-sense/erl_terms.py) simple python to erlang binary term. Works ok so far

So far I only implemented `omnifunc`, if you are interested you may look at other sections.

**Comment by slashmili** [comment]
Done!
