### ISSUE TITLE
:Mix compile errors don't work with vim quickfix

### ISSUE THREAD

**Issue by drichardson** [slashmili/alchemist.vim#99]
When `:Mix compile` produces errors, they don't showup in the quickfix window.

## Steps to Reproduce
1. `mix new quickfix`
2. edit `quickfix/lib/quickfix.ex` to have a syntax error
3. Open vim in the `quickfix` directory.
4: In vim, `:Mix compile`
5. Observe *Compliation error* report.
6. In vim, `:cope` to open quickfix window.

## Results
Empty window.

## Expected
List of compliation errors I could navigate using `:cn` and `:cp`.

**Comment by drichardson** [comment]
I'm not familiar with vim scripting, but if you can point me in the right direction, I can take a stab at addressing this problem myself.

**Comment by slashmili** [comment]
@drichardson that would be great!

Take a look at this resources:

* #68 
* [Errorformats](http://vim.wikia.com/wiki/Errorformats)

**Comment by drichardson** [comment]
I haven't looked at this, and probably won't any time soon since I'm not using elixir at the moment.

**Comment by slashmili** [comment]
I close this issue for now
